### ISSUE TITLE
No module named p-arse

### ISSUE THREAD

**Issue by Maigo96** [a0xnirudh/WebXploiter#14]
After trying to run I get the following error'

Traceback (most recent call last):
  File "WebXploiter.py", line 5, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

**Comment by arbazhussain149** [comment]
Any Update ?


root@arbaz:~/Desktop/Pentest-Suite/scanner/WebXploiter# python WebXploiter.py Traceback (most recent call last):
  File "WebXploiter.py", line 5, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse
root@arbaz:~/Desktop/Pentest-Suite/scanner/WebXploiter# pip install parse
Requirement already satisfied (use --upgrade to upgrade): parse in /usr/local/lib/python2.7/dist-packages

**Comment by arbazkiraak** [comment]
Logs :+1: 

root@arbaz:~/Desktop/Pentest-Suite/scanner/WebXploiter# python WebXploiter.py Traceback (most recent call last):
  File "WebXploiter.py", line 5, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse
root@arbaz:~/Desktop/Pentest-Suite/scanner/WebXploiter# pip install parse
Requirement already satisfied (use --upgrade to upgrade): parse in /usr/local/lib/python2.7/dist-packages
root@arbaz:~/Desktop/Pentest-Suite/scanner/WebXploiter# python WebXploiter.py Traceback (most recent call last):
  File "WebXploiter.py", line 5, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

**Comment by arbazkiraak** [comment]
root@arbaz:~/Desktop/Pentest-Suite/scanner/WebXploiter# python WebXploiter.py 

Traceback (most recent call last):
  File "WebXploiter.py", line 5, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

root@arbaz:~/Desktop/Pentest-Suite/scanner/WebXploiter# python
Python 2.7.12+ (default, Sep  1 2016, 20:27:38) 
[GCC 6.2.0 20160822] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> -> ->import parse
> ->->

parse is already There :|

**Comment by a0xnirudh** [comment]
Use python3 to run the tool. I changed it to python3 a while ago but forgot to change it in the README.
